### ISSUE TITLE
Bug: Multiple duplicate findings uploads allowed without confirmation

### ISSUE THREAD

**Issue by ITGSean** [SerpicoProject/Serpico#344] opened 2017-09-14 00:49 UTC
## Bug
Describe the issue and steps to reproduce

1. A non-admin user creates a report finding and then clicks the upload button to include it in the findings DB for approval
2. There is no confirmation if this worked or not, so the user clicks multiple times without Serpico giving any feedback
3. Multiple duplicate entries are seen by the admin users in the findings DB - annoying.

Suggest that an alert box be displayed upon successful finding upload to the DB.  If successive attempts are made to upload the same finding, then display an alert box telling the user that it's already uploaded.

Cheers,

Sean

**Comment by BuffaloWill** [comment] 2017-09-15 14:31
Thank you for the submission. Just landed a new alert pop-up when a finding is uploaded to the report template database.

I am going to close the issue. The ability to upload a finding multiple times even with the same title was done by design. Hopefully the new alert box should be enough to prevent users from unintentionally doing it.

Cheers!

**Closed by BuffaloWill** 2017-09-15 14:31 UTC
