### ISSUE TITLE
Remove Findings

### ISSUE THREAD

**Issue by daudmalik06** [SerpicoProject/Serpico#216] opened 2016-10-06 14:50 UTC
Describe the issue and steps to reproduce
it remove multi findings of same kinf  e.g 2 sqli in same report

steps:
i have add the sqli from finding list and then addes again 
when i generated the report it deleted them both
Thanks

**Comment by Petessss** [comment] 2016-10-06 15:06
@daudmalik06, do other findings show up ok? If you create a report with just one finding that is not SQLi does it print out ok. If so, then you have an issue with the markup in the SQLi finding.

**Comment by daudmalik06** [comment] 2016-10-06 15:29
it's happening with other types too , reporting coming out empty just basic
info written on it.

**Comment by daudmalik06** [comment] 2016-10-06 15:44
i just re installed and it started working ,the problem appeared when i
made some custom findings,

**Comment by BuffaloWill** [comment] 2016-10-06 15:46
@daudmalik06 this could be caused by a break in markup inside of your custom finding also. For example adding "[==" but not including the closing tag of "==]" can break the rest of the findings in the report.

**Comment by daudmalik06** [comment] 2016-10-06 15:47
oh yeah that could be thanks anyway , but if it happens it should be fix right , it should tell there is some error in blabla findings 
Regards

**Comment by BuffaloWill** [comment] 2016-10-06 15:52
No, the application will tell you if it the markup is incorrect (see https://github.com/SerpicoProject/Serpico/issues/146). 

It should be obvious though because the report will look completely wrong (margins incorrect, etc.).

**Closed** 2016-10-07 14:18 UTC
