### ISSUE TITLE
CVSSv2 Vector paste not working correctly

### ISSUE THREAD

**Issue by ITGSean** [SerpicoProject/Serpico#385] opened 2017-11-16 15:47 UTC
## Bug
Pasting a CVSSv2 score from Nessus into a finding changes the vector in the CVSS box:

Here's my example vector string:
CVSS2#AV:N/AC:L/Au:N/C:C/I:C/A:C

Here's how the interface interprets the pasted string:
![image](https://user-images.githubusercontent.com/25362513/32900394-437ddf98-cae5-11e7-9584-b84d5aa05c4d.png)

You have to manually change the AV: section to "Network" as the GUI changes the string to "Local"

**Comment by BuffaloWill** [comment] 2017-11-17 13:40
Thanks @ITGSean. This is a similar issue to before, the Javascript parser gets greedy.

**Comment by BuffaloWill** [comment] 2018-01-16 18:29
I am closing this issue. The break is caused by mismatched format in the input. 

The input:
```
CVSS2#AV:N/AC:L/Au:N/C:C/I:C/A:C
```
should be changed to replace the # with a /. Serpico requires a slash at the beginning of the string. The following are all acceptable representations:
```
CVSS2/AV:N/AC:L/Au:N/C:C/I:C/A:C
/AV:N/AC:L/Au:N/C:C/I:C/A:C
CVSS:2.0/AV:N/AC:L/Au:N/C:C/I:C/A:C
```

**Closed by BuffaloWill** 2018-01-16 18:29 UTC
Labels: bug_verified
