### ISSUE TITLE
[Bug] Add UDV to tables

### ISSUE THREAD

**Issue by r3b00t5** [SerpicoProject/Serpico#294] opened 2017-07-10 16:31 UTC
I may be wrong here, but when I attempt to add a UDV to a table, it doesn't render.

**Comment by r3b00t5** [comment] 2017-07-10 16:33
Example:
§regional_office_2§ 
∞regional_office_2∞
§regional_office_two§ 
∞regional_office_two∞

**Comment by Petessss** [comment] 2017-07-10 17:00
Can you please fill out the following bug report? 

# Please fill out the Bug Form or Feature Request Below
  |  
  | -------------------
  | ## Bug
  | Describe the issue and steps to reproduce
  |  
  | 1. ...
  | 2. ...
  |  
  |  
  | ## Feature Request
  |  
  | Describe the feature and give an example use case
  |  
  | ### Example Use Case
  |  
  | "As a user ..."

**Comment by r3b00t5** [comment] 2017-07-10 17:48
When attempting to render a UDV in a report table, the UDV placeholder shows up blank
Steps to recreate
1. Create a UDV (regional_office_2)
2. In the report template, create a table
3. In the created table , paste the UDV name along with the meta tags (§regional_office_2§)
4. Upload your modified report template.
5. Generate your report/finding

I'm unsure if this is a bug or simply not a feature that currently exists.

**Comment by Petessss** [comment] 2017-07-10 21:04
are you using something like æreport/udvæ ∞regional_office_2∞ to create your table?

**Comment by r3b00t5** [comment] 2017-07-10 21:47
Here's what I've tried. No luck so far.

| æreport/udvæ ∞regional_office_1 |
| ------------------------------- |
| ¬affected_hosts/paragraph¬ µzzzzµ π.π ÷ π.π ≠|

**Comment by Petessss** [comment] 2017-07-10 21:53
Are you using this within the finding section?

**Comment by r3b00t5** [comment] 2017-07-10 21:54
Yes, its in a finding loop.

**Comment by BuffaloWill** [comment] 2017-07-11 17:19
Hi @r3b00t5, regional_office_1 is missing a closing infinity symbol. Could you try:

```
æreport/udvæ ∞regional_office_1∞
```

**Comment by r3b00t5** [comment] 2017-07-11 17:29
Still no luck. Here's more context
3.3	Medium Findings
¬report/findings_list/findings:::CVSS_TOTAL>3.9:::CVSS_TOTAL<7¬

[17-TNW-03] πtitleπ

CVSSv3 Score: πcvss_totalπ

STRIDE Category: πtypeπ

Description

¬overview/paragraph¬ µzzzzµ π.π

ƒcodeƒ π.π

ƒitalicsƒ π.π

•	ƒbulletƒ π.π

ƒh4ƒ π.π

÷ π.π ≠

Remediation

¬remediation/paragraph¬ µzzzzµ π.π
ƒcodeƒ π.π
ƒitalicsƒ π.π
•	ƒbulletƒ π.π
ƒh4ƒ π.π
÷ π.π ≠

Affected Systems

| æreport/udvæ ∞regional_office_1∞ | æreport/udvæ ∞regional_office_2∞ |
| --- | ---|
| ¬affected_hosts/paragraph¬ µzzzzµ π.π ƒh4ƒ π.π ÷ π.π ≠ |
		
Evidence
¬poc/paragraph¬ µzzzzµ π.π
ƒcodeƒ π.π
ƒitalicsƒ π.π
•	ƒbulletƒ π.π
ƒh4ƒ π.π
÷ π.π ≠

∆

**Comment by BuffaloWill** [comment] 2017-07-11 17:51
Could you try only using the table for loop once? Specifically:

| æreport/udvæ ∞regional_office_1∞ | ∞regional_office_2∞ |

**Comment by r3b00t5** [comment] 2017-07-11 17:55
Sorry, that didn't work. Could it be because it's already in a loop within the findings?

**Comment by BuffaloWill** [comment] 2017-07-11 18:05
Not sure, it's possible. Is either UDV being displayed?

**Comment by r3b00t5** [comment] 2017-07-11 18:07
No, so far I can't get any UDV's to display within the findings loop, unless it's within a finding paragraph.

Example:
<<assessment_team_name>> believes FTP presents a risk to confidentiality.

**Comment by r3b00t5** [comment] 2017-07-11 18:44
Just to rule it out, I tried it outside the loop and it works fine.

| æreport/udvæ ∞regional_office_1∞ |
|---|

**Comment by BuffaloWill** [comment] 2017-07-20 19:23
Thanks @r3b00t5. This looks like a bug.

**Comment by r3b00t5** [comment] 2017-07-26 17:24
Thanks for looking into it.

**Comment by r3b00t5** [comment] 2017-08-15 20:04
Hey @BuffaloWill, do you have an update on this?

**Comment by BuffaloWill** [comment] 2017-08-15 20:10
No I don't. I can a look at end of week. I think there is trick with XSLT to get this to work.

**Comment by frisch-raphael** [comment] 2017-10-09 08:32
I think the "loop inside table" thing is working for me. May be because I use a different xslt generator function ? (https://github.com/SerpicoProject/Serpico/pull/313/files)

**Comment by BuffaloWill** [comment] 2017-10-24 12:57
@r3b00t5, which version of word are you using? If you are using Word 2016, try re-doing the tables without copying over from a different version of Word. I've seen breakage between <Word 2016 and Word 2016 in tables specifically. Had an example in Slack chat where re-doing the tables without Word 2016 fixed this issue specifically for the person.

**Closed by BuffaloWill** 2017-10-24 12:57 UTC
Labels: bug_verified
