### ISSUE TITLE
Unable to Change Finding Type

### ISSUE THREAD

**Issue by r3b00t5** [SerpicoProject/Serpico#347] opened 2017-09-19 16:52 UTC
After creating a new finding type and restarting Serpico, I tried to change an existing finding's type to this new type. After saving, it reverts back to its previous type and discard the save, but if you do not change the finding type, it saves normally.

**Comment by Petessss** [comment] 2017-09-20 10:39
Can you provide more details? Please describe the steps to reproduce. Screen shots are also useful. 
Thanks!

**Comment by r3b00t5** [comment] 2017-09-21 16:45
1. Go to admin/config
2. Under `finding_types` add "CM-8(3): Information System Component Inventory \ Automated Unauthorized Component Detection"
3. Restart serpico
4. Create a new finding and select the new type.
5. Click save.
6. Tear out hair.

I was able to get around the issue by renaming the finding type to "CM-08(3): Unauthorized Component Detection"
I had to edit config.json manually
I'm fairly certain that the web configuration options page just didn't know how to handle the input.

**Comment by Petessss** [comment] 2017-09-21 17:07
I like step 6. :) I wonder the "\" has anything to do with it. I'll take a look at the code and see whats happening. Thanks for the steps it will help be repo the issue.

**Comment by BuffaloWill** [comment] 2017-09-21 19:36
It is a datamapper string limitation issue. The admin configuration does not have a string length limit but the finding type column does. Because the type length is greater than 50 characters (Datamapper default) it's not saving to the DB. 

I will submit a PR.

**Comment by r3b00t5** [comment] 2017-09-21 19:37
Ok, makes sense. Thanks for the update.

**Comment by BuffaloWill** [comment] 2017-09-21 19:43
should be fixed. 

Check if you would please @r3b00t5.

**Closed by BuffaloWill** 2017-09-21 19:43 UTC

**Comment by r3b00t5** [comment] 2017-09-21 20:30
I retried by adding the below finding. It's having the same issue. Another thing I observed, if you make a change on the config page and hit save, the finding type will split this long finding where the comma goes.

e.g.
 "This finding type is crazy long I don't even know how Serpico is going to handle it. Well," 
 "I hope it works",

```
  "finding_types": [
    "This finding type is crazy long I don't even know how Serpico is going to handle it. Well, I hope it works",
    "Web Application",
    "Business Logic",
    "Network Services",
    "Best Practice",
    "Compliance",
    "Database",
    "Network Internal",
    "Router Configuration",
    "Social Engineering",
    "Physical",
    "Wireless",
    "Network Security",
    "System Security",
    "Logging and Auditing",
    "Imported"
  ],
```

**Comment by BuffaloWill** [comment] 2017-09-21 20:37
Finding types cannot contain a comma if submitted through the Admin Configuration UI. The types are delimited by commas so Serpico thinks those are different finding types. 

Just to confirm, you:
1. Pulled the newest code
2. Created a new finding with a Type of  "CM-8(3): Information System Component Inventory \ Automated Unauthorized Component Detection"
3. Clicked Save
4. The finding did not appear in the findings list.

**Comment by r3b00t5** [comment] 2017-09-21 20:40
Yes except I named the finding "This finding type is crazy long I don't even know how Serpico is going to handle it."
